apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-webapp
  template:
    metadata:
      labels:
        app: hello-world-webapp
    spec:
      containers:
      - name: hello-world-webapp
        image: yggdrasill/hello-world-webapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-webapp-service
spec:
  type: NodePort
  selector:
    app: hello-world-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
